### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Furkan3131** [PhoenixFire6879/brawl-downloader#3]
[Tool] Connecting to game.brawlstarsgame.com:9339 ...              
Traceback (most recent call last):
  File "main.py", line 91, in <module>                                 downloader.get_response()
  File "main.py", line 56, in get_response
    self.fingerprint = json.loads(r.readFinger()) # fingerprint      File "/storage/emulated/0/Download/Brawl-Downloader-master/utils/reader.py", line 35, in readFinger
    return self.readChar(length)
  File "/storage/emulated/0/Download/Brawl-Downloader-master/utils/reader.py", line 23, in readChar                                       return self.stream.read(length).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
how to fix? help

**Comment by terexdev** [comment]
lox
